-d C:\Users\The-strip\Desktop\LVDS\MiniLED\project\impl\gwsynthesis\lvds_video.vg
-p GW2A-55-PBGA484-8
-pn GW2A-LV55PG484C8/I7
-cst C:\Users\The-strip\Desktop\LVDS\MiniLED\project\src\lvds_video.cst
-cfg C:\Users\The-strip\Desktop\LVDS\MiniLED\project\impl\pnr\device.cfg
-sdc C:\Users\The-strip\Desktop\LVDS\MiniLED\project\src\lvds_video.sdc
-gao_crc 0111001011101000
-bit
-tr
-ph
-timing
-cst_error
-convert_sdp32_36_to_sdp16_18
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
-rtl_gao
